@startuml

class User {
    - int id
    - String país
    - String primerNombre
    - String primerApellido
    - String contraseña
    - String rol
    - String username
}

class Categoria {
    - int id
    - String descripción
    - String titulo
    - User user_id
}

class Recordatorio {
    - int id
    - String archivo
    - String descripción
    - String fecha
    - String hora
    - String titulo
    - Categoria categoria_id
}

User "1" -- "*" Categoria : tiene
Categoria "1" -- "*" Recordatorio : contiene

@enduml

