@startuml

class CategoriaCarros {
    - int : id
    - String : nombre
    - String : descripcion
    - String : rendimiento
    - boolean : estado 
}

class Autos {
    - int : id
    - String : nombre
    - String : modelo
    - int : tamaño
    - int : puertas
    - int : CategoriaCarros_id
}

class Persona {
    - int : id
    - int : cedula
    - String : nombre
    - String : apellido
    - int : telefono
    - String : correo 
}

class AutosPersona {
    - int : id
    - date : fecha
    - int : Autos_id
    - int : Persona_id
}

CategoriaCarros "1" -- "*" Autos : contiene
Autos "*" -- "*" Persona : contiene
Autos "1" -- "*" AutosPersona : tiene relación
Persona "1" -- "*" AutosPersona : tiene relación

@enduml

